version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t poc-eventhandler .
      - docker tag poc-eventhandler:latest 165274966895.dkr.ecr.us-east-1.amazonaws.com/poc-eventhandler:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 165274966895.dkr.ecr.us-east-1.amazonaws.com/poc-eventhandler:latest
artifacts:
  files:
    - '**/*'
